# @format

version: "3.8"

services:
  redis:
    image: redis:6.2.6
    restart: always
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - ./data-redis:/var/lib/redis

  postgres:
    image: postgres:14.0
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./data-postgres:/var/lib/postgresql/data

  postgres_gui:
    image: dpage/pgadmin4:6
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5433:80"
